name: Check all tests

on:
  check_suite:
    types: [completed]

jobs:

  Check-statuses:
    if: ${{ contains(github.event.branches.*.name, 'master') == 1 }}
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Save github.event to event.json
      run: echo '${{ toJson(github.event) }}' > event.json

    - uses: ./.github/check-status
      id: check

    - name: Upload artifact URL file
      if: steps.check.outputs.skip != 'true'
      uses: weslenng/gcp-storage-sync@master
      env:
        GCP_SERVICE_ACCOUNT_KEY_FILE: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_FILE }}
        GCP_STORAGE_BUCKET: ${{ secrets.GCP_STORAGE_BUCKET }}
        SOURCE_DIR: "install"
