name: Tests

on:
  workflow_call:

jobs:

  Test:
    container: ubuntu:bionic
    runs-on: [self-hosted, Linux, X64]
    strategy:
      fail-fast: false
      matrix:
        test: ['docs', 'testarch', 'tests', 'ice40', 'xc7', 'xc7-vendor', 'xc7a200t', 'xc7a200t-vendor', 'ql']
    env:
      MAX_CORES: 80
      GHA_EXTERNAL_DISK: "tools"

    steps:

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Execute test script
        run: stdbuf -i0 -o0 -e0 ./.github/ci/${{ matrix.test }}.sh

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          path: |
            **/results*.gz
            **/plot_*.svg

  Install:
    container: ubuntu:bionic
    runs-on: [self-hosted, Linux, X64]
    needs: Test

    env:
      MAX_CORES: 80
      GHA_EXTERNAL_DISK: "tools"
      GHA_SA: "gh-sa-f4pga-arch-defs-ci"
      UPLOAD_PACKAGES: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

    steps:

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Execute test script
        run: stdbuf -i0 -o0 -e0 ./.github/ci/install.sh

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          path: |
            **/results*.gz
            **/plot_*.svg
